extra-package-dbs: []
packages:
- '.'

resolver: lts-18.28

extra-deps:
- emoji-0.1.0.2@sha256:d995572a5c7dcd28f98eb15c6e387a7b3bda1ac2477ab0d9dba8580d5d7b161f,1273
- git: https://github.com/L0neGamer/wuss.git
  commit: 3a6eee29cea94ab776f2e6b7db691d8a2e3e671e


nix:
  packages: [ zlib, gmp ]
